<?php
require dirname(__DIR__, 2) . '/src/bootstrap.php';
page_start('Radiohead remixes — Pawel Osmolski', 'Radiohead remixes and covers by Pawel Osmolski, with recording notes and credits.', '/radiohead-remixes/');
?>
<main id="main" class="wrap">
<section class="remix-hero" aria-labelledby="remix-title"><a class="text-link" href="/#remix">← Back to the portfolio</a><p class="eyebrow">An independent fan project / By Pawel Osmolski</p><h1 id="remix-title">RADIOHEAD<br>REMIXES<span>.</span></h1><p class="lead">A different life for a familiar song.</p><p class="remix-intro">These remixes are my homage to Radiohead and to the fan community that shared and supported them. I built new arrangements around acoustic performances, imagining how the songs might sound with a full band.</p></section>
<section class="work-grid remix-content" aria-label="Recordings and background">
<div><?php player('Radiohead remixes & covers', 'https://w.soundcloud.com/player/?url=https%3A%2F%2Fapi.soundcloud.com%2Fplaylists%2F2756743&auto_play=false&visual=true', 'https://soundcloud.com/pawel-osmolski', 'present-tense.jpg'); ?><p class="image-credit">Cover painting by <a href="http://lanachircop.com">Lana Chircop</a>, used with permission.</p></div>
<div class="prose"><h2>The story behind the recordings</h2><p>For <a href="https://soundcloud.com/pawel-osmolski/present-tense/">Present Tense</a>, I took inspiration from Radiohead’s soundchecks, <em>In Rainbows</em> and <em>The King of Limbs</em>. The starting point was Thom Yorke’s acoustic performance at Latitude Festival on 19 July 2009, captured by <a href="https://www.youtube.com/watch?v=BPUTSXXrh7U">Nanakey</a>.</p><p>I had used a similar approach on <a href="https://soundcloud.com/pawel-osmolski/follow-me-around">Follow Me Around</a>, <a href="https://soundcloud.com/pawel-osmolski/big-boots-poison-mix">Big Boots</a> and <a href="https://soundcloud.com/pawel-osmolski/videotape-mephisto-mix">Videotape</a>: keeping the character of the original performance and building a new arrangement around it.</p><details data-slide-details><summary>Original recording credits</summary><div class="details-content"><p>These credits follow the original six-track sequence:</p><ul><li>Tracks 1 and 4–6: Thom Yorke — acoustic guitar and vocals.</li><li>Track 2: Thom Yorke — piano and vocals.</li><li>Track 3: Pawel Osmolski — vocals.</li><li>Track 5: Jonny Greenwood — electric guitar.</li><li>All other instrumentation performed and arranged by Pawel Osmolski.</li></ul></div></details><p class="small">An independent fan project, not an official Radiohead release.</p></div></section>
<section class="related"><p class="eyebrow">More to listen to</p><h2>Enjoyed the remixes?</h2><p>Explore my original music as Filip Oscar on <a href="https://filiposcar.bandcamp.com/album/brokenness-trio">Brokenness Trio</a>, or the 8-bit world of <a href="https://pawel-osmolski.bandcamp.com/album/space-explorer-polaris">Space Explorer Polaris</a>.</p><a class="text-link" href="/#music">Back to my music ↗</a></section>
</main>
<?php page_end(); ?>
